# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CellDequeueReusableDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CellDequeueReusableDemo
  pod 'Masonry', '~> 1.0.2'
  pod 'SDWebImage', '~> 3.7'

  target 'CellDequeueReusableDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CellDequeueReusableDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
