# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mmmtttt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mmmtttt
  pod 'PhotoAlbum', '0.5.0'

  target 'mmmttttTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mmmttttUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
